[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules"]
remappings = [
    "forge-std/=node_modules/forge-std/src/",
    "@openzeppelin/=node_modules/@openzeppelin/"
]

[profile.default.fuzz]
runs = 256

[profile.ci]
fuzz = { runs = 5000 }
invariant = { runs = 1000 }

